import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yarn Barn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Yarn Barn
        </h1>

        <p className={styles.description}>
          All the yarn
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Sock</h2>
            <p>Selection of sock yarn</p>
          </div>

          <div className={styles.card}>
            <h2>Cotton</h2>
            <p>Selection of cotton yarn</p>
          </div>

          <div className={styles.card}>
            <h2>Wool</h2>
            <p>Selection of wool yarn</p>
          </div>

          <div className={styles.card}>
            <h2>Patterns</h2>
            <p>
              Browse Patterns
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
