import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Yarn Barn</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to Kirtland's Yarn Barn
          </h1>


          <div className={styles.highlight}>
            <p>Check Out New Arrivals!</p>
            <div className={styles.highlightItem}>
              <Image
                alt='yarn on shelf'
                layout="responsive"
                width={200}
                height={150}
                src="/yarnshelf.avif"
              />
              <p>Description Here</p>
            </div>
          </div>

          <div className={styles.grid}>
            <Link href='/gifts'>
              <div className={styles.card}>
                <h2>Gifts</h2>
                <p>Gift ideas for the fiber crafter in your life</p>
              </div>
            </Link>

            <Link href='/yarn'>
              <div className={styles.card}>
                <h2>Yarn</h2>
                <p>Browse yarn by weight or brand</p>
              </div>
            </Link>

            <div className={styles.card}>
              <h2>Books</h2>
              <p>Selection of books</p>
            </div>

            <div className={styles.card}>
              <h2>Kits</h2>
              <p>
                Browse Kits
              </p>
            </div>

            <div className={styles.card}>
              <h2>Accessories</h2>
              <p>
                Browse Tools and Accessories
              </p>
            </div>

            <div className={styles.card}>
              <h2>Socks</h2>
              <p>
                All things socks
              </p>
            </div>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </div>
  )
}

export default Home
